# Generated by Django 4.0.4 on 2022-05-04 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recomendaciones', '0003_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='principal',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='recomendacion',
        ),
        migrations.AddField(
            model_name='principal',
            name='categ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recomendaciones.categoria'),
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='princ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recomendaciones.principal'),
        ),
    ]
