# Generated by Django 4.0.4 on 2022-05-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_servicio_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
